openapi: 3.0.0

info:
  title: Node.js Backend API
  description: |
    API Documentation for the Campaign Management & Collaboration Platform
    ## Authentication
    Most endpoints require JWT authentication via Bearer token.
    ## Rate Limiting
    API calls are rate-limited to prevent abuse.
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:5000
    description: Local Development Server
  - url: https://api-staging.example.com
    description: Staging Server
  - url: https://api.example.com
    description: Production Server

tags:
  - name: Auth
    description: Authentication and User Management
  - name: Campaigns
    description: Campaign Management and AI Generation
  - name: Owner
    description: Owner Operations (Browse Influencers, Manage Campaigns)
  - name: Collaborations
    description: Influencer Collaboration Management
  - name: Admin
    description: Administrative Operations (Admin Only)

components:
  # Security schemes
  securitySchemes:
    $ref: './components/security.yaml#/securitySchemes'
  # Schemas
  schemas:
    $ref: './components/schemas.yaml#/schemas'
  # Reusable responses
  responses:
    $ref: './components/responses.yaml#/responses'
  # Reusable parameters
  parameters:
    $ref: './components/parameters.yaml#/parameters'

# All API paths
paths:
  # ==================== AUTH ENDPOINTS ====================
  /api/auth/signup:
    $ref: './paths/auth.yaml#/paths/~1api~1auth~1signup'
  /api/auth/login:
    $ref: './paths/auth.yaml#/paths/~1api~1auth~1login'
  /api/auth/select-role:
    $ref: './paths/auth.yaml#/paths/~1api~1auth~1select-role'
  /api/auth/refresh-token:
    $ref: './paths/auth.yaml#/paths/~1api~1auth~1refresh-token'
  /api/auth/google:
    $ref: './paths/auth.yaml#/paths/~1api~1auth~1google'

  /api/auth/google/callback:
    $ref: './paths/auth.yaml#/paths/~1api~1auth~1google~1callback'
  
  /api/auth/logout:
    $ref: './paths/auth.yaml#/paths/~1api~1auth~1logout'
  
  /api/auth/logout-all:
    $ref: './paths/auth.yaml#/paths/~1api~1auth~1logout-all'
  
  /api/auth/sessions:
    $ref: './paths/auth.yaml#/paths/~1api~1auth~1sessions'
  
  /api/auth/sessions/{sessionId}:
    $ref: './paths/auth.yaml#/paths/~1api~1auth~1sessions~1{sessionId}'
  
  /api/auth/profile:
    $ref: './paths/auth.yaml#/paths/~1api~1auth~1profile'
  
  /api/auth/profile/influencer:
    $ref: './paths/auth.yaml#/paths/~1api~1auth~1profile~1influencer'
  
  /api/auth/profile/owner:
    $ref: './paths/auth.yaml#/paths/~1api~1auth~1profile~1owner'

  # ==================== CAMPAIGN ENDPOINTS ====================
  /api/campaigns:
    $ref: './paths/campaigns.yaml#/paths/~1api~1campaigns'
  
  /api/campaigns/create:
    $ref: './paths/campaigns.yaml#/paths/~1api~1campaigns~1create'

  /api/campaigns/{id}/lifecycle:
    $ref: './paths/campaigns.yaml#/paths/~1api~1campaigns~1{id}~1lifecycle'

  /api/collaborations:
    $ref: './paths/collaboration.yaml#/paths/~1api~1collaborations'

  # ==================== OWNER ENDPOINTS ====================
  /api/owner/influencers:
    $ref: './paths/owner.yaml#/paths/~1api~1owner~1influencers'

  /api/owner/influencers/{id}:
    $ref: './paths/owner.yaml#/paths/~1api~1owner~1influencers~1{id}'

  # ==================== ADMIN ENDPOINTS ====================
  /api/admin/analytics:
    $ref: './paths/admin.yaml#/paths/~1api~1admin~1analytics'

  /api/admin/users:
    $ref: './paths/admin.yaml#/paths/~1api~1admin~1users'

  /api/admin/users/{id}:
    $ref: './paths/admin.yaml#/paths/~1api~1admin~1users~1{id}'

  /api/admin/users/{id}/role:
    $ref: './paths/admin.yaml#/paths/~1api~1admin~1users~1{id}~1role'

  /api/admin/users/{id}/status:
    $ref: './paths/admin.yaml#/paths/~1api~1admin~1users~1{id}~1status'

  /api/admin/sessions:
    $ref: './paths/admin.yaml#/paths/~1api~1admin~1sessions'

  /api/admin/chatrooms:
    $ref: './paths/admin.yaml#/paths/~1api~1admin~1chatrooms'

  /api/admin/chatrooms/{id}/messages:
    $ref: './paths/admin.yaml#/paths/~1api~1admin~1chatrooms~1{id}~1messages'

  /api/admin/collaborations:
    $ref: './paths/admin.yaml#/paths/~1api~1admin~1collaborations'

  /api/admin/collaborations/{id}:
    $ref: './paths/admin.yaml#/paths/~1api~1admin~1collaborations~1{id}'

  /api/admin/collaborations/{id}/status:
    $ref: './paths/admin.yaml#/paths/~1api~1admin~1collaborations~1{id}~1status'

  /api/admin/collaboration-requests:
    $ref: './paths/admin.yaml#/paths/~1api~1admin~1collaboration-requests'

  /api/admin/collaboration-requests/{id}/status:
    $ref: './paths/admin.yaml#/paths/~1api~1admin~1collaboration-requests~1{id}~1status'

  /api/admin/campaigns:
    $ref: './paths/admin.yaml#/paths/~1api~1admin~1campaigns'

  /api/admin/campaigns/{id}:
    $ref: './paths/admin.yaml#/paths/~1api~1admin~1campaigns~1{id}'

  /api/admin/campaigns/{id}/status:
    $ref: './paths/admin.yaml#/paths/~1api~1admin~1campaigns~1{id}~1status'

  # /api/admin/logs:
  #   $ref: './paths/admin.yaml#/paths/~1api~1admin~1logs'

  # /api/admin/logs/recent:
  #   $ref: './paths/admin.yaml#/paths/~1api~1admin~1logs~1recent'
